server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jianshen?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1437830918@qq.com
    password: yemnssvdczguhbic
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    database: 0
    host: 127.0.0.1
mybatis:
  type-aliases-package: com.js.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

upload:
  qiniu:
    ak: XsTZZgVBqVo6bi-zrNnf7it2OwLvo88Jfi76vDZw
    sk: NhSzOJDCGCIAoFnC7NAQ5C6gftzmGjPNCdyWNbS2
    bucketname: zj-image
    url: http://qf7hqnp48.hd-bkt.clouddn.com/

