server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jianshen
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: MWL19981002
mybatis:
  type-aliases-package: com.js.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
