server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webzonhe?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.js.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

