server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webzonhe?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.136.128:3306/jianshen
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    password: mwl19981002
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8083
